# Right now, we direct all URL requests to the Go app we are about to
# construct, but in the future we may add support for jQuery and Bootstrap
# to automatically put a nice UI on the / url.

application: {{ app_id.downcase }}
version: 1
runtime: go
api_version: 3

handlers:
- url: /.*
  script: _go_app

